sudo: required

services:
  - docker

env:
  - MARIADB_VERSION=5.1.42
  - MARIADB_VERSION=5.1.44b ALIAS=5.1.44
  - MARIADB_VERSION=5.1.47
  - MARIADB_VERSION=5.1.49
  - MARIADB_VERSION=5.1.50
  - MARIADB_VERSION=5.1.51
  - MARIADB_VERSION=5.1.53
  - MARIADB_VERSION=5.1.55
  - MARIADB_VERSION=5.1.60
  - MARIADB_VERSION=5.1.61
  - MARIADB_VERSION=5.1.62
  - MARIADB_VERSION=5.1.66
  - MARIADB_VERSION=5.1.67 LATEST_MINOR=5.1
  - MARIADB_VERSION=5.2.3
  - MARIADB_VERSION=5.2.4
  - MARIADB_VERSION=5.2.5
  - MARIADB_VERSION=5.2.6
  - MARIADB_VERSION=5.2.7
  - MARIADB_VERSION=5.2.8
  - MARIADB_VERSION=5.2.9
  - MARIADB_VERSION=5.2.10
  - MARIADB_VERSION=5.2.11
  - MARIADB_VERSION=5.2.12
  - MARIADB_VERSION=5.2.13
  - MARIADB_VERSION=5.2.14 LATEST_MINOR=5.2
  - MARIADB_VERSION=5.3.5-ga ALIAS=5.3.5
  - MARIADB_VERSION=5.3.6
  - MARIADB_VERSION=5.3.7
  - MARIADB_VERSION=5.3.8
  - MARIADB_VERSION=5.3.9
  - MARIADB_VERSION=5.3.10
  - MARIADB_VERSION=5.3.11
  - MARIADB_VERSION=5.3.12 LATEST_MINOR=5.3
  - MARIADB_VERSION=5.5.23
  - MARIADB_VERSION=5.5.24
  - MARIADB_VERSION=5.5.25
  - MARIADB_VERSION=5.5.27
  - MARIADB_VERSION=5.5.28
  - MARIADB_VERSION=5.5.28a
  - MARIADB_VERSION=5.5.29
  - MARIADB_VERSION=5.5.30
  - MARIADB_VERSION=5.5.31
  - MARIADB_VERSION=5.5.32
  - MARIADB_VERSION=5.5.33
  - MARIADB_VERSION=5.5.33a
  - MARIADB_VERSION=5.5.34
  - MARIADB_VERSION=5.5.35
  - MARIADB_VERSION=5.5.36
  - MARIADB_VERSION=5.5.37
  - MARIADB_VERSION=5.5.38
  - MARIADB_VERSION=5.5.39
  - MARIADB_VERSION=5.5.40
  - MARIADB_VERSION=5.5.41
  - MARIADB_VERSION=5.5.42
  - MARIADB_VERSION=5.5.43
  - MARIADB_VERSION=5.5.44
  - MARIADB_VERSION=5.5.45
  - MARIADB_VERSION=5.5.46
  - MARIADB_VERSION=5.5.47
  - MARIADB_VERSION=5.5.48
  - MARIADB_VERSION=5.5.49
  - MARIADB_VERSION=5.5.50
  - MARIADB_VERSION=5.5.51
  - MARIADB_VERSION=5.5.52
  - MARIADB_VERSION=5.5.53
  - MARIADB_VERSION=5.5.54 LATEST_MINOR=5.5 LATEST_MAJOR=5
  - MARIADB_VERSION=10.0.10
  - MARIADB_VERSION=10.0.11
  - MARIADB_VERSION=10.0.12
  - MARIADB_VERSION=10.0.13
  - MARIADB_VERSION=10.0.14
  - MARIADB_VERSION=10.0.15
  - MARIADB_VERSION=10.0.16
  - MARIADB_VERSION=10.0.17
  - MARIADB_VERSION=10.0.18
  - MARIADB_VERSION=10.0.19
  - MARIADB_VERSION=10.0.20
  - MARIADB_VERSION=10.0.21
  - MARIADB_VERSION=10.0.22
  - MARIADB_VERSION=10.0.23
  - MARIADB_VERSION=10.0.24
  - MARIADB_VERSION=10.0.25
  - MARIADB_VERSION=10.0.26
  - MARIADB_VERSION=10.0.27
  - MARIADB_VERSION=10.0.28
  - MARIADB_VERSION=10.0.29 LATEST_MINOR=10.0
  - MARIADB_VERSION=10.1.8
  - MARIADB_VERSION=10.1.9
  - MARIADB_VERSION=10.1.10
  - MARIADB_VERSION=10.1.11
  - MARIADB_VERSION=10.1.12
  - MARIADB_VERSION=10.1.13
  - MARIADB_VERSION=10.1.14
  - MARIADB_VERSION=10.1.16
  - MARIADB_VERSION=10.1.17
  - MARIADB_VERSION=10.1.18
  - MARIADB_VERSION=10.1.19
  - MARIADB_VERSION=10.1.20
  - MARIADB_VERSION=10.1.21 LATEST_MINOR=10.1 LATEST_MAJOR=10 LATEST=true

before_install:
  - sudo apt-get update -y --allow-unauthenticated
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" docker-engine

before_script:
  - docker build --force-rm=true --build-arg MARIADB_VERSION=${MARIADB_VERSION} -t deeky666/mariadb:${ALIAS:-MARIADB_VERSION} .

  - docker run -d -p 3307:3306 --name mariadb deeky666/mariadb:${MARIADB_VERSION}
  - sleep 5
  - status="$(docker inspect -f '{{ .State.Health.Status}}' mariadb)" && [ "$status" = 'healthy' ]
  - echo "status" | mysql -h127.0.0.1 -P 3307 -uroot
  - mysql -h127.0.0.1 -P 3307 -uroot -e "CREATE DATABASE foo; SHOW DATABASES;" | grep foo > /dev/null

  - if [[ ! -z "$TRAVIS_TAG" && ! -z "$LATEST_MINOR" ]]; then docker tag deeky666/mariadb:${MARIADB_VERSION} deeky666/mariadb:${LATEST_MINOR}; fi
  - if [[ ! -z "$TRAVIS_TAG" && ! -z "$LATEST_MAJOR" ]]; then docker tag deeky666/mariadb:${MARIADB_VERSION} deeky666/mariadb:${LATEST_MAJOR}; fi
  - if [[ ! -z "$TRAVIS_TAG" && ! -z "$LATEST" ]]; then docker tag deeky666/mariadb:${MARIADB_VERSION} deeky666/mariadb:latest; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then docker push deeky666/mariadb; fi

script: true

matrix:
  fast_finish: true
